# Base image for python development
# Includes a selection of my dotfiles
# vi: ft=dockerfile
FROM ARG_BASE
RUN yum install -y epel-release
RUN yum install -y \
    git \
    python-ipython \
    python-pip \
    tmux
RUN pip install --upgrade setuptools pip
RUN pip install ipdb pudb
WORKDIR /root
RUN rm .config/pudb/pudb.cfg
ADD bash/.bashrc .
ADD tmux/.tmux.conf .
ADD python/.config/pudb .config/pudb/
