[main]
font=JetBrains Mono Nerd Font:size=13, Noto Color Emoji:size=13
initial-window-size-chars=211x54
title=Terminal
pad=5x5 center
gamma-correct-blending=false
include=/usr/share/foot/themes/gruvbox
shell=systemd-run --quiet --scope --user tide

[colors]
# Darker foreground (fg2)
foreground=d5c4a1
background=000000

[colors2]
background=ffffff

[csd]
size=0
border-width=0
border-color=7c6f64

[key-bindings]
fullscreen=F11
show-urls-launch=Control+Shift+k
spawn-terminal=none

[mouse-bindings]
primary-paste=none

[mouse]
hide-when-typing=yes
