[main]
font=JetBrains Mono Nerd Font:size=13, Noto Color Emoji:size=13
initial-window-size-chars=90x25
title=Terminal
app-id=Terminal
pad=5x5 center
gamma-correct-blending=false
include=/usr/share/foot/themes/gruvbox

[colors-dark]
# Darker foreground (fg2)
foreground=d5c4a1
background=1d2021

[colors-light]
background=f2e5bc

[csd]
size=0
border-width=1
border-color=7c6f64

[mouse]
hide-when-typing=yes

[key-bindings]
fullscreen=F11
show-urls-launch=Control+Shift+k

[mouse-bindings]
primary-paste=none
