#!/bin/bash

get_cont() {
    echo "$1" | cut -d "/" -f 2
}

get_abs_path() {
    echo /$(echo "$1" | cut -d "/" -f 4-)
}

exec_cont() {
    CMD=$1
    STORED=$2
    CONT=$(get_cont "$STORED")
    STORED=$(get_abs_path "$STORED")
    podman exec "$CONT" "$CMD" "$STORED"
}

if [ "$1" == "list" ]; then
    for IMAGE in $(podman images --filter=dangling=false \
                   --format="{{.Repository}}:{{.Tag}}"); do
        echo "drwxr-xr-x  6 root root      4096 May 21 18:44 IMAGES/$IMAGE"
    done

    for CONT in $(podman ps --format="{{.Names}}"); do
        DEST=$(podman unshare podman mount "$CONT")
        DIRNAME="CONTAINERS/${CONT}/DATA"
        podman unshare << EOF
            pushd $DEST >/dev/null
            FORMAT="%M %n %u %g %s %Am-%Ad-%AY %AH:%AM:%.2AS $DIRNAME/"
            find . \! -type l -printf "\${FORMAT}%p\n"
            find . -type l -printf "\${FORMAT}%p -> %l\n"
            popd >/dev/null
EOF
    done
elif [ "$1" == "copyout" ]; then
    STORED=$3
    EXTRACT=$4
    CONT=$(get_cont "$STORED")
    STORED=$(get_abs_path "$STORED")
    podman cp "$CONT:$STORED" "$EXTRACT"
elif [ "$1" == "copyin" ]; then
    STORED=$3
    SOURCE=$4
    CONT=$(get_cont "$STORED")
    STORED=$(get_abs_path "$STORED")
    podman cp "$SOURCE" "$CONT:$STORED"
elif [ "$1" == "rm" ]; then
    exec_cont "$1" "$3"
elif [ "$1" == "rmdir" ]; then
    exec_cont "$1" "$3"
elif [ "$1" == "mkdir" ]; then
    exec_cont "$1" "$3"
fi

exit 0
