###############################################################################
# Terminal stuff
###############################################################################

setw -g xterm-keys on
set -ga terminal-overrides ",foot:Tc"

###############################################################################
# Key bindings
###############################################################################

set -g prefix C-a
unbind C-b
bind C-a send-prefix

setw -g mode-keys vi

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-m resize-pane -Z

bind -n C-Tab select-window -n
bind -n C-BTab select-window -p
bind -n M-q select-window -l
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6

bind -n M-enter popup -E -yC -b padded
bind -n M-s popup -E -yC -w 140 -h 80% -b padded tide git
bind -n M-w popup -E -y0 tide palette

bind s choose-tree -sNZO name
bind -n M-o split-window -h
bind -n M-e split-window -v

bind R run-shell "tide refresh"
bind k confirm-before -p "Kill session #{session_name}? (y/n)" "kill-session"

# vim-like copy mode ('C-v' already does the same as 'v' so we're fine)
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection-and-cancel

###############################################################################
# Quality of life
###############################################################################

# more friendly terminal titles
set -g set-titles on

# start with window 1 (instead of 0)
set -g base-index 1
# start with pane 1
set -g pane-base-index 1

# set scrollback history to 10k
set -g history-limit 10000

# needed for vim mode switching
set -sg escape-time 10

# attach to last session when current is killed
set -g detach-on-destroy off

set -g window-size smallest

###############################################################################
# Status
###############################################################################

setw -g automatic-rename off
setw -g allow-rename off

###############################################################################
# Colors
###############################################################################

set -g status on
set -g status-position bottom
set -g status-style fg=default,bg="#{THEME_COLOR_BG0}"
set -g status-left-length 60
set -g status-right-length 60
set -g status-left  "#{p80:#[fg=default,bg=#{THEME_COLOR_ACTIVE_BG}] #{?@repo,#{@repo},#{session_name}} #[default] #(tide status left '#{session_path}')}"
set -g status-right "#{?window_zoomed_flag,,}   #{pane_current_command}#{?@path,   #{@path},} "
set -g status-interval 60

set -g window-status-format         "#[fg=default,bg=default]  #{window_name}  #[default]"
set -g window-status-current-format "#[fg=#{THEME_COLOR_ACTIVE_FG},bg=#{THEME_COLOR_ACTIVE_BG0}]  #{window_name}  #[default]"
set -g window-status-separator      ""

set -g pane-border-lines heavy
set -g pane-border-style fg="#{THEME_COLOR_BG0}",bg="#{THEME_COLOR_BG}"
set -g pane-active-border-style fg="#{THEME_COLOR_BG0}",bg="#{THEME_COLOR_BG}"

set -g popup-style bg="#{THEME_COLOR_BG0}"
set -g popup-border-lines none
set -g popup-border-style fg="#{THEME_COLOR_DIM2}",bg="#{THEME_COLOR_BG0}"

set -g mode-style fg="#{THEME_COLOR_ACTIVE_FG}",bg="#{THEME_COLOR_ACTIVE_BG}"
set -g message-style fg=default,bg=default

set -g monitor-bell off
